### ISSUE TITLE
Unable to add Kaldi model because files are larger than 50MB limit

### ISSUE THREAD

**Issue by robertocaiwu** [b-it-bots/mas_models#2]
I am unable to add the Kaldi models (as requested here: b-it-bots/mas_domestic_robotics/pull/179) because according to this issue [git-lfs/git-lfs/issues/1449], lfs does not work on public forks unless the original repo already has lfs objects, or I have push access to the original repo.

**Comment by alex-mitrevski** [comment]
I've added you as a collaborator with write access, so you should be able to push now.
